In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [2]:
data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
data.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      3     107     118     127     134     139     143     146     150   
1      6     155     157     156     156     156     157     156     158   
2      2     187     188     188     187     187     186     187     188   
3      2     211     211     212     212     211     210     211     210   
4     13     164     167     170     172     176     179     180     184   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     153  ...       207       207       207       207       206       206   
1     158  ...        69       149       128        87        94       163   
2     187  ...       202       201       200       199       198       199   
3     210  ...       235       234       233       231       230       226   
4     185  ...        92       105       105       108       133       163   

   pixel781  pixel782  pixel783  pixel784  
0       206       204       203       202  
1       175       103       135       149  
2       198       195       194       195  
3       225       222       229       163  
4       157       163       164       179  

[5 rows x 785 columns]

In [5]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

# data_dev = data[0:1000].T
# Y_dev = data_dev[0]
# X_dev = data_dev[1:n]
# X_dev = X_dev / 255.

# data_train = data[1000:m].T
# Y_train = data_train[0]
# X_train = data_train[1:n]
# X_train = X_train / 255.
# _,m_train = X_train.shape
data_dev = test_data.T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data.T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
# data_train = data[1000:m].T
# Y_train = data_train[0]
# X_train = data_train[1:n]
# X_train = X_train / 255.
_,m_train = X_train.shape
# print(m_train)

In [6]:
# def init_params():
#     w1 = np.random.randn(10,784)
#     b1 = np.random.randn(10,1)
#     w2 = np.random.randn(10,10)
#     b2 = np.random.randn(10,1)
#     return w1,b1,w2,b2
# def ReLU(x):
#     g=np.maximum(0,x)
#     return g
# def softmax(x):
#     return np.exp(x)/np.sum(np.exp(x))
# def forward_prop(w1,b1,w2,b2,X):
#     z1= w1.dot(X)+b1
#     a1= ReLU(z1)
#     z2= w2.dot(a1)+b2
#     a2 = softmax(z2)
#     return z1,a1,z2,a2

# def one_hot(Y):
#     one_hot_y = np.zeros(Y.size,Y.max()+1)
#     one_hot_y[np.arange(Y.size),Y]=1
#     one_hot_y=one_hot_y.T
#     return one_hot_y
# def deriv_ReLU(z):
#     return z>0
# def back_prop(z1,a1,z2,a2,X,Y):
#     m=Y.size
#     one_hot_y = one_hot(Y)
#     dz2 =a2 -one_hot_y
#     dw2 = 1/m*dz2.dot(a1.T)
#     db2 = 1/m*np.sum(dz2,2)
#     dz1 = dw2.T.dot(dz2)*deriv_ReLU(z1)
#     dw1 = 1/m*dz1.dot(X.T)
#     db1 = 1/m*np.sum(dz1,2)
#     return dw1,db1,dw2,db2
# def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
#     w1 = w1 - alpha*dw1
#     b1 = b1 - alpha*db1
#     w2 = w2 - alpha*dw2
#     b2 = b2 - alpha*db2
#     return w1,b1,w2,b2


In [10]:
def init_params():
    W1 = np.random.rand(50, 784) - 0.5
    b1 = np.random.rand(50, 1) - 0.5
    W2 = np.random.rand(50, 50) - 0.5
    b2 = np.random.rand(50, 1) - 0.5
    W3 = np.random.rand(25, 50) - 0.5
    b3 = np.random.rand(25, 1) - 0.5

    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

init_params()

(array([[-0.37549927,  0.13904978,  0.38670248, ..., -0.20363595,
         -0.06976724, -0.33055837],
        [-0.39004678,  0.14332429,  0.48415643, ..., -0.45786101,
          0.49313206,  0.10290623],
        [-0.42198803,  0.12069597, -0.44609668, ..., -0.00776961,
          0.23902106,  0.04358261],
        ...,
        [ 0.45432948, -0.01035935, -0.43723976, ..., -0.01242426,
         -0.49469641, -0.40077304],
        [ 0.19254806,  0.06920061, -0.30965244, ...,  0.01418708,
         -0.36022604, -0.32138825],
        [-0.49292179, -0.07700485, -0.2996626 , ...,  0.18089367,
          0.01328311,  0.43123878]]),
 array([[-0.44945775],
        [ 0.49364174],
        [-0.01092947],
        [ 0.39670273],
        [-0.45543201],
        [ 0.05706901],
        [-0.23067356],
        [ 0.46610544],
        [-0.08489366],
        [-0.36877626],
        [ 0.46692728],
        [ 0.08116874],
        [ 0.38195876],
        [ 0.34597475],
        [-0.12116546],
        [-0.43914426],
     

In [8]:
# def get_prediction(a2):
#     return np.argmax(a2,0)
# def get_accuracy(predictions, Y):
#     print(predictions,Y)
#     return np.sum(predictions==Y)/Y.size


# def gradient_descent(X,Y,iterations,alpha):
#     w1,b1,w2,b2 = init_params()
#     for i in range(iterations):
#         z1,a1,z2,a2=forward_prop(w1,b1,w2,b2,X)
#         dw1,db1,dw2,db2=back_prop(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)
#         if i%50==0:
#             print("Iteration:",i)
#             print("Accuracy:",get_accuracy(get_prediction(a2)))
#     return w1,b1,w2,b2

In [9]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [11]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.05, 1000)

Iteration:  0
[ 3  5  5 ... 12 12 12] [16 15 16 ... 14  0 15]
0.03223456565288654
Iteration:  10
[ 0 16 17 ... 16 13 12] [16 15 16 ... 14  0 15]
0.039628482972136225
Iteration:  20
[21 16 17 ... 16 16 16] [16 15 16 ... 14  0 15]
0.03063194317974868
Iteration:  30
[16 16  6 ... 16 16 16] [16 15 16 ... 14  0 15]
0.03638681478783464
Iteration:  40
[16 16  6 ... 16 16 16] [16 15 16 ... 14  0 15]
0.03886359497359315
Iteration:  50
[18 16  6 ... 16 16 16] [16 15 16 ... 14  0 15]
0.04068475687488618
Iteration:  60
[18 16  6 ... 16 16 16] [16 15 16 ... 14  0 15]
0.040502640684756876
Iteration:  70
[18 16  6 ... 16 21 16] [16 15 16 ... 14  0 15]
0.043562192678929156
Iteration:  80
[18 16 23 ... 21 21 16] [16 15 16 ... 14  0 15]
0.04643962848297214
Iteration:  90
[18 16 23 ... 21 21 16] [16 15 16 ... 14  0 15]
0.04847932981242033
Iteration:  100
[18 16 13 ... 21 21 16] [16 15 16 ... 14  0 15]
0.05033691495173921
Iteration:  110
[18 16 23 ... 21 21 16] [16 15 16 ... 14  0 15]
0.05215807685303223


In [40]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [42]:
# test_prediction(0, W1, b1, W2, b2)
# test_prediction(1, W1, b1, W2, b2)
# test_prediction(2, W1, b1, W2, b2)
# test_prediction(3, W1, b1, W2, b2)
pred_data= make_predictions(X_dev,W1, b1, W2, b2)
print(pred_data)

[ 3 21 15 ...  9  3  9]


In [47]:
submit = pd.read_csv('sample_submission.csv')
submit.label=(pred_data)
submit.to_csv('predictions.csv', index=False)